//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_PK { get; set; }
        public string UserID { get; set; }
        public string UserPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Department { get; set; }
        public int KylieGroup { get; set; }
        public string FullName { get; set; }
        public string UsersTitle { get; set; }
        public string UsersEmail { get; set; }
        public string GMailAddress { get; set; }
        public string GMailPassword { get; set; }
        public Nullable<int> Valid { get; set; }
        public string WebLoginGUID { get; set; }
        public Nullable<int> EmployeeMappedID { get; set; }
    }
}
